import './App.css';
import Menu from "./components/Menu/Menu";
import { FaBeer } from 'react-icons/fa';
import { BiAngry } from "react-icons/bi";
import { BiBasketball } from "react-icons/bi";
import { BiAnalyse } from "react-icons/bi";
import {useState} from "react";

function App() {

  const [menuActive, setMenuActive ] = useState(false)

  const clickHandler = (e) => {
    setMenuActive(!menuActive)
  }

  const preventDefHandler = (e) => {
    e.preventDefault()
  }

  const items = [
    {value: 'Главная', href: '/main', icon: <FaBeer/>},
    {value: 'Услуги', href: '/service', icon: <BiAngry/>},
    {value: 'Магазин', href: '/shop', icon: <BiBasketball/>},
    {value: 'О нас', href: '/main', icon: <BiAnalyse/>},
  ]

  return (
<div className={'app'}>
  <nav>
    <div onClick={clickHandler} className="burger-btn">
      <span></span>
    </div>
  </nav>
  <main>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut autem consequuntur doloremque eligendi facere fugiat ipsum similique? Accusamus aspernatur atque deserunt distinctio doloremque dolores enim expedita facilis fugiat harum ipsum itaque laudantium libero magnam mollitia, natus nobis non placeat quidem quod tenetur, totam vel velit, veniam voluptatem. Assumenda cumque ducimus ea eligendi eveniet pariatur perferendis ratione sunt? Accusamus amet aspernatur aut, consectetur, corporis dolorum est eum facere fugiat hic ipsam iure modi quaerat rerum similique suscipit voluptatibus. Beatae corporis dolorem illo modi natus quo suscipit. Aperiam assumenda, consectetur consequuntur debitis, distinctio error exercitationem iure maxime minus nobis perspiciatis porro quam recusandae sapiente veritatis, voluptas voluptates! Commodi consequatur cupiditate esse fugiat necessitatibus, perferendis placeat reiciendis rerum? Blanditiis consequatur delectus dolorum nobis nulla officiis provident. Alias assumenda commodi dicta dolor esse exercitationem fuga id impedit, iste, iure iusto magnam maxime natus necessitatibus perferendis quia quis quos ratione repellat sint suscipit temporibus tenetur unde vel voluptates! Consectetur cum dignissimos distinctio enim ipsam itaque magni molestias nemo reprehenderit! Ad aspernatur, blanditiis doloremque esse in nisi officia quasi quidem quisquam quos repudiandae voluptate. Architecto beatae debitis dolor fugiat labore minus, obcaecati optio saepe voluptates. Aspernatur esse facere inventore laborum nobis porro voluptas. Minima, obcaecati veniam?</p>
  </main>
  <Menu preventDefHandler={preventDefHandler} clickHandler={clickHandler} header={'Бургер Меню'} items={items} menuActive={menuActive} setMenuActive={setMenuActive}/>
</div>
  );
}

export default App;
